# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kartikey's Blog
tagline: Kartikey's blog on programming and freelancing!
email: tannakartikey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog by Kartikey Tanna on programming and freelancing.
  I am a programmer and an avid meditator.
  Enjoy cooking and eating vegetarian food.
  Hate traveling but would go to the end of the world for a good pizza! I have 2 years of experience in being a good husband! 😃
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kartikey.dev" # the base hostname & protocol for your site, e.g. http://example.com

author: tannakartikey

social_links:
  twitter: tannakartikey
  github: tannakartikey
  linkedin: tannakartikey
  devto: tannakartikey
  stackoverflow: "2422068"

twitter:
  username: tannakartikey
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/me.jpg

social:
  links:
    - https://twitter.com/tannakartikey
    - https://github.com/tannakartikey
    - https://www.linkedin.com/in/tannakartikey/
    - https://www.facebook.com/tanna.kartikeya/

google_analytics: UA-162859155-1

disqus:
  shortname: https-www-kartikey-dev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

header_pages:
  - faq.md
  - blog.md

last-modified-at:
  date-format: '%b %d, %Y'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
