# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kartikey Tanna
email: tannakartikey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Kartikey Tanna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kartikey.dev" # the base hostname & protocol for your site, e.g. http://example.com

author:
  email: "tannakartikey@gmail.com"

minima:
  social_links:
    twitter: tannakartikey
    github: tannakartikey
    stackoverflow: tannakartikey
    linkedin: tannakartikey

google_analytics: UA-162859155-1

disqus:
  shortname: https-www-kartikey-dev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - faq.md
  - blog.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
